services:
  # 1. The Database
  db:
    image: postgres:15
    container_name: genstore_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mystore
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. RabbitMQ (Message Broker for Celery)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: genstore_rabbit
    ports:
      - "5672:5672"   # RabbitMQ port
      - "15672:15672" # Management UI (Dashboard)

  # 3. The FastAPI Web App
  api:
    build: .
    container_name: genstore_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq


  # 4. The Celery Worker
  worker:
    build: .
    container_name: genstore_worker
    # FIX 1: Point to 'app.celery_app.celery_app' (based on your screenshot)
    # FIX 2: Use sh -c and PYTHONPATH to ensure the 'app' folder is found
    command: sh -c "PYTHONPATH=. uv run celery -A app.celery_app.celery_app worker --loglevel=info"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - db
volumes:
  postgres_data: