"""add_payments_table

Revision ID: 90a11218d27f
Revises: e24f0fea8484
Create Date: 2025-12-23 10:57:59.081246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a11218d27f'
down_revision: Union[str, Sequence[str], None] = 'e24f0fea8484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.drop_constraint(op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('orders', 'address_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.drop_constraint(op.f('orders_address_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'orders', 'user_addresses', ['address_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('orders_address_id_fkey'), 'orders', 'user_addresses', ['address_id'], ['id'])
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.alter_column('orders', 'address_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_product_id_fkey'), 'order_items', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.alter_column('order_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
