"""add cart order relationships

Revision ID: 93f44e490f5a
Revises: 98e17b1cc33a
Create Date: 2025-12-16 17:19:15.847886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f44e490f5a'
down_revision: Union[str, Sequence[str], None] = '98e17b1cc33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('cart_items', sa.Column('cart_id', sa.UUID(), nullable=True))
    op.alter_column('cart_items', 'price_at_add',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_unique_constraint('uq_cart_product', 'cart_items', ['cart_id', 'product_id'])
    op.drop_constraint(op.f('cart_items_product_id_fkey'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('cart_items_user_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'])
    op.drop_column('cart_items', 'total_price')
    op.drop_column('cart_items', 'user_id')
    op.add_column('order_items', sa.Column('product_name', sa.String(), nullable=False))
    op.alter_column('order_items', 'price_at_purchase',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('pending', 'paid', 'shipped', 'delivered', 'cancelled', name='orderstatus'),
               existing_nullable=True)
    op.add_column('products', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.add_column('user_addresses', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.alter_column('user_addresses', 'address_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('home', 'work', 'other', name='addresstype'),
               existing_nullable=True)
    op.create_index(op.f('ix_user_addresses_phone'), 'user_addresses', ['phone'], unique=False)
    op.create_index(op.f('ix_user_addresses_user_id'), 'user_addresses', ['user_id'], unique=False)
    op.create_index('ix_user_default_address', 'user_addresses', ['user_id', 'is_default'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_provider'), 'users', ['provider'], unique=False)
    op.create_index(op.f('ix_users_provider_id'), 'users', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_provider'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_index('ix_user_default_address', table_name='user_addresses')
    op.drop_index(op.f('ix_user_addresses_user_id'), table_name='user_addresses')
    op.drop_index(op.f('ix_user_addresses_phone'), table_name='user_addresses')
    op.alter_column('user_addresses', 'address_type',
               existing_type=sa.Enum('home', 'work', 'other', name='addresstype'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('user_addresses', 'is_default')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'sku')
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('pending', 'paid', 'shipped', 'delivered', 'cancelled', name='orderstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('order_items', 'price_at_purchase',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('order_items', 'product_name')
    op.add_column('cart_items', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('cart_items', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_user_id_fkey'), 'cart_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('cart_items_product_id_fkey'), 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_cart_product', 'cart_items', type_='unique')
    op.alter_column('cart_items', 'price_at_add',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('cart_items', 'cart_id')
    op.drop_table('carts')
    # ### end Alembic commands ###
